{
 "title": "Linux & Windows Performance (via Otel, MetricsHub)",
 "description": "General OS performance metrics to assess the availability and performance of Linux and Windows systems. Leverages OpenTelemetry metrics collected with MetricsHub and stored in Prometheus.",
 "tags": [
  "System",
  "Otel",
  "MetricsHub"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System",
    "query": {
     "query": "label_values(system_uptime_seconds,connector_id)"
    }
   },
   {
    "name": "network_id",
    "query": {
     "query": "label_values(system_network_io_bytes_total{host_name=\"$host_name\"},id)"
    }
   },
   {
    "name": "physical_disk_system_device",
    "query": {
     "query": "label_values(system_disk_io_bytes_total{host_name=\"$host_name\"},system_device)"
    }
   },
   {
    "name": "host_name",
    "label": "Hostname",
    "query": {
     "query": "label_values({connector_id=~\"$system\"},host_name)"
    }
   },
   {
    "name": "agent",
    "label": "agent",
    "query": {
     "query": "label_values(system_uptime_seconds{host_name=\"$host_name\"},agent_host_name)"
    }
   },
   { "name": "filesystemFilter", "label": "Exclude Filesystem Types", "query": ".*tmpfs|nfs.*|overlay" }
  ]
 },
 "panels": [
  { "title": "Host Global Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_join(system_uptime_seconds{host_name=\"$host_name\"}, \"joined_os\", \" \", \"name\", \"version\", \"os_version\") ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(system_cpu_utilization_ratio{host_name=\"$host_name\", system_cpu_state=\"idle\"})",
     "legendFormat": "Connector"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_limit_bytes{host_name=\"$host_name\"}",
     "legendFormat": "Connector"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(system_filesystem_usage_bytes{host_name=\"$host_name\", system_filesystem_type !~\"$filesystemFilter\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime_seconds{host_name=\"$host_name\"}",
     "legendFormat": "Connector"
    }
   ]
  },
  {
   "title": "Connector",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metricshub_connector_status{host_name=\"$host_name\", connector_id=~\"Linux|Windows\", state=\"ok\"}",
     "legendFormat": "Connector"
    }
   ]
  },
  {
   "title": "Dashboard",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "options": {
    "content": "<a href=\"https://metricshub.com/\" target=\"_blank\">\n  <div style=\"\n    display: block;\n    margin: 0 auto; \n    \n    background: transparent url(https://metricshub.com/images/logo-darkgrey.svg) no-repeat center center;\n    background-size: contain;\n    \n    width: 85px;   \n    height: 85px;\n    border-radius: 3px;\n  \">\n  </div>\n</a>"
   }
  },
  { "title": "Protocols", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum_over_time(metricshub_host_up{host_name=\"$host_name\"}[$__range]) / count_over_time(metricshub_host_up{host_name=\"$host_name\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "min_over_time(\r\n  (\r\n    (metricshub_host_response_time_seconds{host_name=\"$host_name\"} > 0) * 1 or\r\n    (metricshub_host_response_time_seconds{host_name=\"$host_name\"} <= 0) * +Inf\r\n  )[$__range:1m]\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(metricshub_host_response_time_seconds{host_name=\"$host_name\"}[$__range])",
     "legendFormat": "{{protocol}}"
    },
    {
     "expr": "max_over_time(metricshub_host_response_time_seconds{host_name=\"$host_name\"}[$__range])",
     "legendFormat": "{{protocol}}"
    },
    {
     "expr": "metricshub_host_response_time_seconds{host_name=\"$host_name\"}",
     "legendFormat": "{{protocol}}"
    },
    {
     "expr": "metricshub_host_up{host_name=\"$host_name\"}",
     "legendFormat": "{{protocol}}"
    },
    {
     "expr": "metricshub_host_up{host_name=\"$host_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Max CPU Utilization",
   "type": "timeseries",
   "description": "Utilization of the busiest core/processor, to identify CPU contention",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (host_name) (1 - rate(system_cpu_time_seconds_total{host_name=\"$host_name\", system_cpu_state=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Max Core CPU Utilization"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(system_memory_utilization_ratio{host_name=\"$host_name\", system_memory_state!=\"free\"})",
     "legendFormat": "Memory Utilization"
    }
   ]
  },
  {
   "title": "Max Disk Utilization",
   "type": "timeseries",
   "description": "Utilization of the busiest disk, to identify disk contention",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(rate(system_disk_io_time_seconds_total{host_name=\"$host_name\"}[$__rate_interval]))",
     "legendFormat": "Max Disk Time Utilization"
    }
   ]
  },
  {
   "title": "Network Total Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(system_network_io_bytes_total{host_name=\"$host_name\", network_io_direction=\"transmit\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(system_network_io_bytes_total{host_name=\"$host_name\", network_io_direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Time",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "seconde" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (system_cpu_state) (delta(system_cpu_time_seconds_total{host_name=\"$host_name\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Core Utilization (Instant)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (name) (irate(system_cpu_time_seconds_total{host_name=\"$host_name\", system_cpu_state!=\"idle\"}[1h]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (host_name, system_cpu_state) (rate(system_cpu_time_seconds_total{host_name=\"$host_name\", system_cpu_state!=\"idle\"}[$__rate_interval]))",
     "legendFormat": "{{system_cpu_state}}"
    },
    {
     "expr": "max by (host_name) (1 - rate(system_cpu_time_seconds_total{host_name=\"$host_name\", system_cpu_state=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Max Core CPU Utilization"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{host_name=\"$host_name\"}",
     "legendFormat": "{{system_memory_state}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_memory_utilization_ratio{host_name=\"$host_name\", system_memory_state!=\"free\"}",
     "legendFormat": "{{system_memory_state}}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_bytes{host_name=\"$host_name\", system_memory_state=~\"cached|buffers\"}",
     "legendFormat": "{{system_memory_state}}"
    }
   ]
  },
  { "title": "Filesystems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Filesystems",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_filesystem_usage_bytes{host_name=\"$host_name\", system_filesystem_state=\"free\", system_filesystem_type !~\"$filesystemFilter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_filesystem_usage_bytes{host_name=\"$host_name\", system_filesystem_state=\"used\", system_filesystem_type !~\"$filesystemFilter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(system_filesystem_utilization_ratio{host_name=\"$host_name\",system_filesystem_state=~\"used|reserved\", system_filesystem_type !~\"$filesystemFilter\"}) by (system_device) - sum(system_filesystem_utilization_ratio{host_name=\"$host_name\",system_filesystem_state=~\"used|reserved\", system_filesystem_type !~\"$filesystemFilter\"} offset $__range) by (system_device) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(system_filesystem_utilization_ratio{host_name=\"$host_name\",system_filesystem_state=~\"used|reserved\", system_filesystem_type !~\"$filesystemFilter\"}) by (system_device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(system_filesystem_usage_bytes{host_name=\"$host_name\",system_filesystem_state=~\"used|reserved|free\", system_filesystem_type !~\"$filesystemFilter\"}) by (system_device)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network Traffic - Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Network Total Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(system_network_io_bytes_total{host_name=\"$host_name\", network_io_direction=\"transmit\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(system_network_io_bytes_total{host_name=\"$host_name\", network_io_direction=\"receive\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Tx Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(system_network_errors_total{host_name=\"$host_name\", network_io_direction=\"transmit\"}[$__range]))\r\n/\r\nsum (delta(system_network_packets_total{host_name=\"$host_name\", network_io_direction=\"transmit\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Dropped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(system_network_dropped_total{host_name=\"$host_name\", network_io_direction=\"transmit\"}[$__range]))\r\n/\r\nsum (delta(system_network_packets_total{host_name=\"$host_name\", network_io_direction=\"transmit\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rx Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(system_network_errors_total{host_name=\"$host_name\", network_io_direction=\"receive\"}[$__range]))\r\n/\r\nsum (delta(system_network_packets_total{host_name=\"$host_name\", network_io_direction=\"receive\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rx Dropped",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(system_network_dropped_total{host_name=\"$host_name\", network_io_direction=\"receive\"}[$__range]))\r\n/\r\nsum (delta(system_network_packets_total{host_name=\"$host_name\", network_io_direction=\"receive\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network Traffic - Individual", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Traffic: $network_id",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "repeat": "network_id",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_network_io_bytes_total{host_name=\"$host_name\", network_io_direction=\"transmit\", id=\"$network_id\"}[$__rate_interval])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(system_network_io_bytes_total{host_name=\"$host_name\", network_io_direction=\"receive\", id=\"$network_id\"}[$__rate_interval])",
     "legendFormat": "Transmitted"
    }
   ]
  },
  { "title": "Disk Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Disk Activity: $physical_disk_system_device",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 61 },
   "repeat": "physical_disk_system_device",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (disk_io_direction) (rate(system_disk_io_bytes_total{host_name=\"$host_name\", system_device=\"$physical_disk_system_device\"}[$__rate_interval]))",
     "legendFormat": "{{disk_io_direction}}"
    }
   ]
  },
  { "title": "Agent Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 67 },
   "repeat": "agent",
   "targets": [
    {
     "expr": "timestamp(metricshub_agent_info{agent_host_name=\"$agent\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}